py-httplib2: extracted files do not have proper 'group' and 'other' perms.
Causes build failures in other ports, e.g.:

--->  Building py26-nose
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from setup3lib import setup
  File "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_python_py-nose/py26-nose/work/nose-1.2.1/setup3lib.py", line 2, in <module>
    from setuptools import setup as _setup
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2835, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 704, in subscribe
    callback(dist)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2835, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2259, in activate
    self.insert_on(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2366, in insert_on
    self.check_version_conflict()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2405, in check_version_conflict
    for modname in self._get_metadata('top_level.txt'):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 2253, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 1213, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 1205, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pkg_resources.py", line 1320, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/httplib2-0.7.6-py2.6.egg-info/top_level.txt'


git-svn-id: http://svn.macports.org/repository/macports/trunk/dports@97949 d073be05-634f-4543-b044-5fe20cf6d1d6