When trying "sudo port install evince" with a gnome-free /opt/local, I got the following error message after lots of gnome dependencies were built:
> checking for LIB... configure: error: Package requirements (gtk+-2.0 >= 2.8.15
>		libgnomeui-2.0 >= 2.14.0) were not met:
> No package 'libgnomeui-2.0' found
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> Alternatively, you may set the environment variables LIB_CFLAGS
> and LIB_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> Error: Status 1 encountered during processing.

Obviously, there's a missing dependency on libgnomeui.  After sudo port install
libgnomeui, everything builds, installs, and works great.  This change just
records that dependency.


git-svn-id: http://svn.macports.org/repository/macports/trunk/dports@20323 d073be05-634f-4543-b044-5fe20cf6d1d6